### ISSUE TITLE
failed to create/migrate Ipfs index 

### ISSUE THREAD

**Issue by Xadoy** [izihawa/summa#143]
Hi,

Thanks for creating such powerful and creative tool.

I followed the [quick start doc](https://izihawa.github.io/summa/guides/quick-start.html) and it worked great (except for a small problem #141). Then, I tried [IPFS Publish + WASM Browsing ](https://izihawa.github.io/summa/guides/ipfs-wasm-guide.html), but got the following error:

`thread 'tokio-runtime-workers-0' panicked at 'not implemented', summa-server/src/services/index.rs:284:54` with the `izihawa/summa-server:testing` docker container.

**Comment by ppodolsky** [comment]
Hi! Yeah, this is an `unimplemeted()` branch of code. I had scheduled to implement it in a while but given that you have already faced this bug and that you are the first reporter in this repo, I'll try to implement it until the end of the day :)
Thanks for the report!

**Comment by ppodolsky** [comment]
`testing` image will be updated in an hour. But it is still not tested properly, final version will land in 1-2 days.
