### ISSUE TITLE
Query parser asking for not null field

### ISSUE THREAD

**Issue by hadim** [izihawa/summa#158]
Is that possible using the summa query parser to ask for entries where a specific field is not null. Something like `cid:<NOT NULL>`?

**Comment by ppodolsky** [comment]
I have added `ExistsQuery` which may be used in direct queries. Through `SummaQL` this new query is not available but you may do `RegexQuery`: `cid:/.+/`. Hope it helps you, reopen the issue if any questions remain

**Comment by hadim** [comment]
Thanks!

**Comment by hadim** [comment]
@ppodolsky do you think it would be possible to add `RegexQuery` support for `SummaQL`?

**Comment by ppodolsky** [comment]
> @ppodolsky do you think it would be possible to add `RegexQuery` support for `SummaQL`?

Seems I wasn't clear enough.
It is already supported and you may do RegexQuery through SummaQL, just compose your query like this: `blabla cid:/.+/`

**Comment by hadim** [comment]
I tested it and it works well. Thanks!
