### ISSUE TITLE
Elastic search compatibility

### ISSUE THREAD

**Issue by hamza1311** [izihawa/summa#163]
We have an application where we would like to run search in browser if the query can't be passed to elastic search (offline, etc). Are there any plans of providing an API compatible with elastic search? Because of it's ubiquity, other search engines (like [quickwit, based on tantivy](https://quickwit.io/docs/reference/es_compatible_api)) also provide it. It would be great if summa were to also provide such an API

**Comment by ppodolsky** [comment]
In general, I have nothing against having this layer in API. It is slightly out of scope for me, because I do not have any ES instances in our stack, though I will review and accept PRs implementing additional ES-compatible endpoints.

If you are in, then we can discuss a solution.
